version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node 20..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - ln -sf /usr/bin/node /usr/local/bin/node
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v
      - npm ci

  build:
    commands:
      - echo "Building Angular app..."
      - npx ng build --configuration production

artifacts:
  files:
    - '**/*'
  # UPDATED LINE BELOW:
  # Adjusted to match the output folder seen in your logs.
  # Added '/browser' because your logs show server bundles are being generated.
  base-directory: dist/angular-demo/browser