version: 0.2

phases:
  install:
    commands:
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      - ng build --configuration production

artifacts:
  base-directory: dist
  files:
    - '**/*'
