version: 0.2

phases:
  install:
    commands:
      - echo "Using Node version:"
      - node -v
      - npm -v
      - npm ci

  build:
    commands:
      - echo "Building Angular app..."
      - npx ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: dist/*
