version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node 20..."
      - curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      - apt-get install -y nodejs
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v
      - npm ci

  build:
    commands:
      - echo "Building Angular app..."
      - npx ng build --configuration production

artifacts:
  files:
    - '**/*'
  base-directory: dist/
